set -g fish_user_paths "/usr/local/sbin" $fish_user_paths
set -g -x PATH "$HOME/.config/yarn/global/node_modules/.bin" $PATH
alias npm=yarn

#### git alias ####
alias gstt="git status"
alias gsth="git stash"
alias gsthl="git stash list"
alias gsthp="git stash pop"
alias gd="git diff"
alias gdh="git diff --histogram"
alias gdc="git diff --cached"
alias ga="git add"
alias gau="git add -u"
alias gap="git add -p"
alias gcm="git commit -m"
alias gcmb="git commit"
alias gcho="git checkout"
alias gchp="git cherry-pick"
alias gf="git fetch"
alias gfa="git fetch --all"
alias gfap="git fetch --all --prune"
alias gpl="git pull"
alias gps="git push"
alias gpsf="git push -f"
alias gme="git merge"
alias gmec="git merge --continue"
alias gmea="git merge --abort"
alias greb="git rebase"
alias grebi="git rebase -i"
alias grebc="git rebase --continue"
alias greba="git rebase --abort"
alias gres="git reset"
alias gresh="git reset --hard"
alias gress="git reset --soft"
alias gbr="git branch"
alias glo="git log --graph --oneline --decorate"
alias gloa="git log --graph --oneline --decorate --all"

